export const RECIPES = [
  { out:'wood_pickaxe', n:1, station:null, req:{wood:6} },
  { out:'wood_sword', n:1, station:null, req:{wood:5} },
  { out:'torch', n:4, station:null, req:{wood:1,coal:1} },
  { out:'ladder', n:4, station:null, req:{wood:2} },
  { out:'crafting_table', n:1, station:null, req:{wood:8} },
  { out:'arrow', n:8, station:null, req:{wood:1,coal:1} },
  { out:'tnt', n:2, station:null, req:{ember_core:1,coal:2} },
  { out:'health_potion', n:1, station:null, req:{wood:2,coal:1} },

  { out:'stone_pickaxe', n:1, station:'table', req:{stone:5,wood:2} },
  { out:'stone_sword', n:1, station:'table', req:{stone:4,wood:2} },
  { out:'furnace', n:1, station:'table', req:{stone:15} },
  { out:'bow', n:1, station:'table', req:{wood:6} },

  // ---- SMELTING: every metal ore refines to a bar at the furnace ----
  { out:'copper_bar',   n:1, station:'furnace', req:{copper_ore:2,coal:1} },
  { out:'tin_bar',      n:1, station:'furnace', req:{tin_ore:2,coal:1} },
  { out:'lead_bar',     n:1, station:'furnace', req:{lead_ore:2,coal:1} },
  { out:'iron_bar',     n:1, station:'furnace', req:{iron_ore:2,coal:1} },
  { out:'silver_bar',   n:1, station:'furnace', req:{silver_ore:2,coal:1} },
  { out:'tungsten_bar', n:1, station:'furnace', req:{tungsten_ore:2,coal:1} },
  { out:'gold_bar',     n:1, station:'furnace', req:{gold_ore:2,coal:1} },
  { out:'platinum_bar', n:1, station:'furnace', req:{platinum_ore:2,coal:1} },
  { out:'cobalt_bar',   n:1, station:'furnace', req:{cobalt_ore:2,coal:2} },
  { out:'titanium_bar', n:1, station:'furnace', req:{titanium_ore:2,coal:2} },
  { out:'meteorite_bar',n:1, station:'furnace', req:{meteorite_ore:2,coal:3} },

  // ---- METAL TOOLS: copper -> iron -> gold -> titanium/meteorite ----
  { out:'iron_pickaxe', n:1, station:'table', req:{iron_bar:5,wood:2} },
  { out:'iron_sword', n:1, station:'table', req:{iron_bar:4,wood:2} },
  { out:'gold_pickaxe', n:1, station:'table', req:{gold_bar:5,wood:2} },
  { out:'gold_sword', n:1, station:'table', req:{gold_bar:4,wood:2} },
  { out:'titanium_pickaxe', n:1, station:'table', req:{titanium_bar:6,wood:3} },
  { out:'meteorite_pickaxe', n:1, station:'table', req:{meteorite_bar:6,titanium_bar:2} },
  { out:'meteorite_sword', n:1, station:'table', req:{meteorite_bar:8,titanium_bar:2} },

  // ---- ARMOR: crafted at a table from bars (helmet/chest/boots per set) ----
  { out:'copper_helmet', n:1, station:'table', req:{copper_bar:4} },
  { out:'copper_chestplate', n:1, station:'table', req:{copper_bar:7} },
  { out:'copper_boots', n:1, station:'table', req:{copper_bar:3} },
  { out:'iron_helmet', n:1, station:'table', req:{iron_bar:4} },
  { out:'iron_chestplate', n:1, station:'table', req:{iron_bar:7} },
  { out:'iron_boots', n:1, station:'table', req:{iron_bar:3} },
  { out:'gold_helmet', n:1, station:'table', req:{gold_bar:4} },
  { out:'gold_chestplate', n:1, station:'table', req:{gold_bar:7} },
  { out:'gold_boots', n:1, station:'table', req:{gold_bar:3} },
  { out:'titanium_helmet', n:1, station:'table', req:{titanium_bar:5} },
  { out:'titanium_chestplate', n:1, station:'table', req:{titanium_bar:8} },
  { out:'titanium_boots', n:1, station:'table', req:{titanium_bar:4} },
  { out:'meteorite_helmet', n:1, station:'table', req:{meteorite_bar:5} },
  { out:'meteorite_chestplate', n:1, station:'table', req:{meteorite_bar:8} },
  { out:'meteorite_boots', n:1, station:'table', req:{meteorite_bar:4} },

  // ---- LEGENDARIES: craftable at a table from boss-core materials ----
  { out:'thunder_hammer', n:1, station:'table', req:{gold_bar:6,thunder_shard:3,titanium_bar:2} },
  { out:'water_trident',  n:1, station:'table', req:{frost_core:2,titanium_bar:3,gold_bar:2} },
  { out:'fire_sword',     n:1, station:'table', req:{ember_core:2,meteorite_bar:3,gold_bar:2} },
  { out:'tempest_bow',    n:1, station:'table', req:{storm_core:2,thunder_shard:3,gold_bar:2} },
];
